"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(%ddetpnx9^@5dui^5(_&!vu+njw0h$02(=r+71ncvqcm3mvb1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['119.223.104.14', '172.30.1.130', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_vite',
    'surveys'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'survey_db',       # 생성하신 DB 이름
        'USER': 'survey_user',     # 생성하신 계정
        'PASSWORD': 'pilot1234!',  # 계정 비밀번호
        'HOST': '119.223.104.14',     # 로컬 개발시는 서버IP, 서버내부 실행시는 'localhost'
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# settings.py 하단

STATIC_URL = '/static/'

# 개발 환경에서 static 폴더 위치를 지정
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# 로그인 성공 시 이동할 페이지
LOGIN_REDIRECT_URL = '/' 
# 로그아웃 시 이동할 페이지
LOGOUT_REDIRECT_URL = '/accounts/login/'

# [중요] STATIC_ROOT 추가
# 서버에서 collectstatic을 실행했을 때 모든 파일이 모이는 물리적 경로임.
STATIC_ROOT = BASE_DIR / "staticfiles"

# 3. Django-Vite 상세 설정
# 빌드된 파일들이 모이는 실제 물리적 경로
DJANGO_VITE_ASSETS_PATH = BASE_DIR / "static" / "dist"

# 개발 모드 설정 (True일 때는 Vite 개발 서버(3000포트)를 보고, False일 때는 dist 폴더의 파일을 봄)
DJANGO_VITE_DEV_MODE = DEBUG 

# Vite 개발 서버 주소
DJANGO_VITE_DEV_SERVER_HOST = "127.0.0.1"
DJANGO_VITE_DEV_SERVER_PORT = 3000