# Generated by Django 6.0 on 2025-12-27 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_code', models.CharField(max_length=20, unique=True, verbose_name='조사코드')),
                ('survey_name', models.CharField(max_length=200, verbose_name='조사명')),
                ('survey_year', models.CharField(max_length=4, verbose_name='조사연도')),
                ('survey_degree', models.IntegerField(default=1, verbose_name='조사차수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '통계 조사 마스터',
                'verbose_name_plural': '통계 조사 마스터 목록',
            },
        ),
        migrations.CreateModel(
            name='SurveyDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_schema', models.JSONField(default=list, help_text='명부에 사용될 헤더 항목 정의', verbose_name='명부항목설계')),
                ('survey_schema', models.JSONField(default=list, help_text='조사표 문항 및 입력 방식 정의', verbose_name='조사표설계')),
                ('edit_rules', models.JSONField(default=list, verbose_name='에디팅규칙')),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='design', to='surveys.surveymaster')),
            ],
            options={
                'verbose_name': '통계 설계',
            },
        ),
        migrations.CreateModel(
            name='SurveyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_id', models.CharField(max_length=50, verbose_name='응답자 고유ID')),
                ('list_values', models.JSONField(default=dict, verbose_name='명부데이터')),
                ('survey_values', models.JSONField(default=dict, verbose_name='조사표답변')),
                ('status', models.CharField(choices=[('READY', '준비'), ('ING', '조사중'), ('DONE', '완료'), ('ERROR', '에러')], default='READY', max_length=20, verbose_name='조사상태')),
                ('is_edited', models.BooleanField(default=False, verbose_name='에디팅검증여부')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_records', to='surveys.surveymaster')),
            ],
            options={
                'verbose_name': '수집 데이터',
            },
        ),
    ]
