# Generated by Django 6.0 on 2025-12-27 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='조사명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_name', models.CharField(max_length=100, verbose_name='항목명(논리)')),
                ('physical_name', models.CharField(max_length=100, verbose_name='필드명(물리)')),
                ('field_type', models.CharField(choices=[('text', '문자열(Text)'), ('number', '숫자(Number)'), ('date', '날짜(Date)')], default='text', max_length=20)),
                ('max_length', models.IntegerField(default=255, verbose_name='최대길이')),
                ('display_order', models.IntegerField(default=0, verbose_name='순서')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='surveys.survey')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
