# Generated by Django 6.0 on 2025-12-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_survey_surveyfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyfield',
            name='survey',
        ),
        migrations.AlterModelOptions(
            name='surveydata',
            options={},
        ),
        migrations.RemoveField(
            model_name='surveydata',
            name='is_edited',
        ),
        migrations.AlterField(
            model_name='surveydata',
            name='status',
            field=models.CharField(choices=[('READY', '준비'), ('ING', '조사중'), ('DONE', '완료'), ('ERROR', '에러')], default='READY', max_length=20),
        ),
        migrations.AlterField(
            model_name='surveydesign',
            name='list_schema',
            field=models.JSONField(default=list, verbose_name='명부항목설계'),
        ),
        migrations.AlterField(
            model_name='surveydesign',
            name='survey_schema',
            field=models.JSONField(default=list, verbose_name='조사표설계'),
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
        migrations.DeleteModel(
            name='SurveyField',
        ),
    ]
