# Generated by Django 6.0 on 2025-12-27 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_remove_surveyfield_survey_alter_surveydata_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveydata',
            name='survey',
        ),
        migrations.AlterField(
            model_name='surveydata',
            name='respondent_id',
            field=models.CharField(max_length=50, verbose_name='명부레코드ID'),
        ),
        migrations.AlterField(
            model_name='surveydata',
            name='status',
            field=models.CharField(default='READY', max_length=20),
        ),
        migrations.CreateModel(
            name='SurveyRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roster_name', models.CharField(max_length=100, verbose_name='명부명')),
                ('mapping_config', models.JSONField(default=list, verbose_name='항목맵핑설정')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_roster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyroster', verbose_name='상위명부')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='surveys.surveymaster')),
            ],
        ),
        migrations.AddField(
            model_name='surveydata',
            name='roster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_records', to='surveys.surveyroster'),
        ),
    ]
