# Generated by Django 6.0 on 2025-12-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_remove_surveydata_survey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyroster',
            name='roster_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='명부ID'),
        ),
    ]
