# Generated by Django 6.0 on 2025-12-27 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_surveyroster_roster_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(max_length=20, unique=True, verbose_name='조사표ID')),
                ('form_name', models.CharField(max_length=100, verbose_name='조사표명')),
                ('design_data', models.JSONField(default=list, verbose_name='조사표설계데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='surveys.surveyroster')),
            ],
        ),
    ]
