# Generated by Django 6.0 on 2025-12-27 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_surveyquestionnaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestionnaire',
            name='design_data',
        ),
        migrations.CreateModel(
            name='QuestionnaireVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(verbose_name='버전번호')),
                ('design_data', models.JSONField(default=list, verbose_name='설계데이터')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='확정여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='surveys.surveyquestionnaire')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
    ]
