# Generated by Django 6.0 on 2025-12-28 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_remove_surveyquestionnaire_design_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveydesign',
            options={},
        ),
    ]
